"""empty message

Revision ID: 707ea5f5a6bf
Revises: 
Create Date: 2024-03-26 20:38:15.572780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707ea5f5a6bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=250), nullable=True),
    sa.Column('fact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facts')
    # ### end Alembic commands ###
